/**
 * Auto-author (Phase 1): backlog question → AI draft → `content/auto-draft.en.ts`.
 *
 * This is the DRAFTING half of the auto-content pipeline (see
 * docs/auto-content-cron-plan.md). It deliberately does NOT touch Firestore:
 * it only writes a reviewable `content/*.ts` file for a human to merge, after
 * which the existing seeder publishes it. The human merge is the quality gate.
 *
 * It reuses generateWikiContent() but ADAPTS its output, because that helper is
 * shaped for user-driven chat-publish, not the editorial DraftArticle schema:
 *   - it returns no `question`   → filled from the backlog topic
 *   - it returns no `topicKey`   → filled from the backlog topic
 *   - it returns no `language`   → forced to 'en' (English-first by design)
 *   - `content` may lack a `# `  → an H1 is prepended when missing
 *   - `summary` can be 1000 chars → trimmed to ≤320 (validateDraft's cap)
 *   - `tags` can be 10           → trimmed to ≤8
 * Its JSON-parse fallback (provider.ts) dumps the raw model response, so every
 * draft passes a quality gate and weak generations are SKIPPED, never written.
 *
 * Images are intentionally omitted (text-first): seed with --no-images, or add
 * hero prompts by hand before seeding. Locale expansion stays the existing
 * human-reviewed translate flow — this tool emits English only.
 *
 * Usage:
 *   npx tsx scripts/auto-author.ts                 # dry-run (no file written)
 *   npx tsx scripts/auto-author.ts --apply         # write content/auto-draft.en.ts
 *   npx tsx scripts/auto-author.ts --apply --limit=2
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { config } from 'dotenv';
import { generateWikiContent } from '../src/lib/ai/provider';
import { pendingTopics, type BacklogTopic } from '../content/backlog';
import type { DraftArticle } from '../content/types';
import type { AIModel, Message } from '../src/types';

config({ path: '.env.local', override: true });

// ─── CLI ─────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const APPLY = args.includes('--apply');
function flag(name: string): string | undefined {
  const a = args.find((x) => x.startsWith(`--${name}=`));
  return a ? a.slice(name.length + 3) : undefined;
}

// Hard cost cap: a leaked trigger or a bad --limit must not fan out. Each draft
// is one model call; keep runs small and reviewable.
const HARD_CAP = 5;
const LIMIT = Math.min(HARD_CAP, Math.max(1, Number(flag('limit') ?? 3) || 3));
const MODEL = (flag('model') ?? 'claude') as AIModel;

const OUT_PATH = join(dirname(dirname(fileURLToPath(import.meta.url))), 'content', 'auto-draft.en.ts');

// ─── Adapters (close the generateWikiContent → DraftArticle gap) ───────────
/** Trim to ≤320 chars on a word boundary (validateDraft rejects longer). */
function clampSummary(s: string): string {
  const t = s.trim();
  if (t.length <= 320) return t;
  const cut = t.slice(0, 300);
  const at = cut.lastIndexOf(' ');
  return `${(at > 200 ? cut.slice(0, at) : cut).trim()}…`;
}

/** DraftArticle.content must start with "# " — prepend an H1 if the model didn't. */
function ensureH1(content: string, title: string): string {
  const t = content.trim();
  return /^#\s/.test(t) ? t : `# ${title}\n\n${t}`;
}

/** Reject weak/garbage generations (incl. provider's raw-dump fallback path). */
function isWeak(g: { title: string; content: string; summary: string }, topic: BacklogTopic): string | null {
  if (!/(^|\n)#{1,3}\s/.test(g.content)) return 'no markdown headings';
  if (g.content.trim().length < 400) return 'content too short';
  if (g.summary.trim().length < 20) return 'summary too short';
  // provider's fallback sets title = question.slice(0,100).
  if (topic.question.startsWith(g.title.slice(0, 40))) return 'title looks like the raw question';
  return null;
}

async function withRetry<T>(label: string, fn: () => Promise<T>, attempts = 3): Promise<T> {
  let lastErr: unknown;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      if (i === attempts - 1) break;
      console.warn(`    ↻ retry ${i + 1}/${attempts - 1} ${label}: ${(err as Error).message?.slice(0, 120)}`);
      await new Promise((r) => setTimeout(r, 1500 * (i + 1)));
    }
  }
  throw lastErr;
}

function serialize(drafts: DraftArticle[], iso: string): string {
  return (
    `import type { DraftArticle } from './types';\n\n` +
    `// AUTO-GENERATED by scripts/auto-author.ts on ${iso}. REVIEW facts + sources\n` +
    `// before seeding. Each run OVERWRITES this file (a transient carrier). Seed:\n` +
    `//   npx tsx scripts/seed-editorial.ts --batch=auto-draft --no-images --apply\n\n` +
    `export const autoDraftEn: DraftArticle[] = ${JSON.stringify(drafts, null, 2)};\n`
  );
}

// ─── Main ────────────────────────────────────────────────────────────────
async function main(): Promise<void> {
  const topics = pendingTopics(LIMIT);
  console.log(`▸ model=${MODEL} limit=${LIMIT} pending=${topics.length}${APPLY ? '' : ' (DRY RUN)'}`);
  if (!topics.length) {
    console.log('Nothing pending in content/backlog.ts — done.');
    return;
  }
  if (!process.env.ANTHROPIC_API_KEY && MODEL === 'claude') {
    console.error('ANTHROPIC_API_KEY missing — set it in .env.local or the workflow env.');
    process.exit(1);
  }

  const drafts: DraftArticle[] = [];
  for (const topic of topics) {
    const convo: Message[] = [{ id: 'q', role: 'user', content: topic.question, timestamp: Date.now() }];
    let g;
    try {
      g = await withRetry(`generate ${topic.topicKey}`, () => generateWikiContent(MODEL, convo));
    } catch (err) {
      console.log(`  ✗ ${topic.topicKey}: generation failed — ${(err as Error).message?.slice(0, 120)}`);
      continue;
    }

    const weak = isWeak(g, topic);
    if (weak) {
      console.log(`  ⏭  ${topic.topicKey}: skipped (${weak})`);
      continue;
    }

    drafts.push({
      topicKey: topic.topicKey,
      title: g.title,
      question: topic.question,
      summary: clampSummary(g.summary),
      tags: g.tags.slice(0, 8),
      language: 'en',
      content: ensureH1(g.content, g.title),
      ...(g.sources.length ? { sources: g.sources } : {}),
    });
    console.log(`  ✓ ${topic.topicKey}: "${g.title}" (${g.sources.length} sources)`);
  }

  console.log(`\n▸ drafted ${drafts.length}/${topics.length}`);
  if (!drafts.length) {
    console.log('No drafts passed the quality gate — nothing written.');
    return;
  }

  if (!APPLY) {
    console.log(`(dry run) would write ${OUT_PATH}. Re-run with --apply to write it.`);
    return;
  }

  writeFileSync(OUT_PATH, serialize(drafts, new Date().toISOString()));
  console.log(`✓ wrote ${OUT_PATH}`);
  console.log('Next: open a PR, review, merge, then seed with');
  console.log('  npx tsx scripts/seed-editorial.ts --batch=auto-draft --no-images --apply');
}

main().catch((err) => {
  console.error('FATAL:', err);
  process.exit(1);
});
